/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditableRouteImport } from './routes/editable'
import { Route as IndexRouteImport } from './routes/index'

const EditableRoute = EditableRouteImport.update({
  id: '/editable',
  path: '/editable',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editable': typeof EditableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editable': typeof EditableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editable': typeof EditableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editable'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editable'
  id: '__root__' | '/' | '/editable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditableRoute: typeof EditableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editable': {
      id: '/editable'
      path: '/editable'
      fullPath: '/editable'
      preLoaderRoute: typeof EditableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditableRoute: EditableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
